### ISSUE TITLE
SMPLX _label

### ISSUE THREAD

**Issue by SWWdz** [caizhongang/gta-human_toolbox#1]
Thanks for your work! I am interested in your work!
How do I get SMPLX_label information from GTA-V?  Can you tell me some documents or advice?

**Comment by caizhongang** [comment]
Hi @SWWdz , we also open-sourced our toolchain [here](https://github.com/Wei-Chen-hub/GTA-Human-tools). The toolchain obtains 3D keypoints via GTA's API. Afterwards, run [SMPLify-X](https://github.com/vchoutas/smplify-x) to fit SMPL-X on these keypoints using 3D MSE losses.

**Comment by SWWdz** [comment]
Thanks for your reply! I see your toolchain can get 98 available joints from GTA, but it is not the same as SMPL-X model, I am confused at how you align SMPL-X joints to your 98 joints.

**Comment by caizhongang** [comment]
> Thanks for your reply! I see your toolchain can get 98 available joints from GTA, but it is not the same as SMPL-X model, I am confused at how you align SMPL-X joints to your 98 joints.

Hi, please see keypoint conventions in MMHuman3D for [SMPL-X](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/core/conventions/keypoints_mapping/smplx.py#L1-L146) and [GTA](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/core/conventions/keypoints_mapping/gta.py#L104-L205), the mapping can be done by matching keypoints of the same name. In addition to the 98 keypoints obtained from the API, we interpolate two more keypoints: the head top and the nose.

**Comment by SWWdz** [comment]
Thanks! I have got these joints from GTA. I am very appreciative of your work. I am interested in GTA generating data. Can you describe some documents or websites where you learned GTA to generate data?

**Comment by caizhongang** [comment]
Our code is mainly based on the wonderful work of [JTA](https://github.com/fabbrimatteo/JTA-Dataset). Hope this helps.

**Comment by SWWdz** [comment]
But JTA only give 22 joints code, how do you get other joints' code?

**Comment by caizhongang** [comment]
We take reference with the [official bone id](https://wiki.rage.mp/index.php?title=Bones). This is the [code](https://github.com/Wei-Chen-hub/GTA-Human-tools/blob/main/collection/DatasetAnnotator/scenario.cpp#L1451-L1544) to extract the keypoints, and this is where we [define](https://github.com/Wei-Chen-hub/GTA-Human-tools/blob/main/collection/DatasetAnnotator/dictionary.h#L9-L114) the joints.

**Comment by SWWdz** [comment]
Hello. Can you provide the code to process GTA dataset 3D keypoints to  SMPLX_label. Thank you!
